// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKPo_yr94YOavCF7VcTBP12A6ljMblYOE',
    appId: '1:41150382944:web:018ecec3d0a8ce14325405',
    messagingSenderId: '41150382944',
    projectId: 'adminpanel-9aa72',
    authDomain: 'adminpanel-9aa72.firebaseapp.com',
    databaseURL: 'https://adminpanel-9aa72-default-rtdb.firebaseio.com',
    storageBucket: 'adminpanel-9aa72.appspot.com',
    measurementId: 'G-KRWSNTJWXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbG3lyzIGAD1H02Kma1PUeVf_d-LO7guI',
    appId: '1:41150382944:android:6d5b1170dce33d0f325405',
    messagingSenderId: '41150382944',
    projectId: 'adminpanel-9aa72',
    databaseURL: 'https://adminpanel-9aa72-default-rtdb.firebaseio.com',
    storageBucket: 'adminpanel-9aa72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd7jt9QYbvL76O0ZXlIdrRvVzTNfmhDwQ',
    appId: '1:41150382944:ios:3f3d951104aa6815325405',
    messagingSenderId: '41150382944',
    projectId: 'adminpanel-9aa72',
    databaseURL: 'https://adminpanel-9aa72-default-rtdb.firebaseio.com',
    storageBucket: 'adminpanel-9aa72.appspot.com',
    iosClientId: '41150382944-o5u2qjclshb7r0mee1q46gkmpv882gck.apps.googleusercontent.com',
    iosBundleId: 'com.adminpanel.adminpanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd7jt9QYbvL76O0ZXlIdrRvVzTNfmhDwQ',
    appId: '1:41150382944:ios:0cbeca9427e73b68325405',
    messagingSenderId: '41150382944',
    projectId: 'adminpanel-9aa72',
    databaseURL: 'https://adminpanel-9aa72-default-rtdb.firebaseio.com',
    storageBucket: 'adminpanel-9aa72.appspot.com',
    iosClientId: '41150382944-shkct7v4k22pamju79s4bgjl6nq6pf8a.apps.googleusercontent.com',
    iosBundleId: 'com.adminpanel.adminpanel.RunnerTests',
  );
}
